package com.qunyu.taoduoduo.global;


public class Constant {
    public static final boolean DEBUG = true;
    public static String TYPE = null;
    //public static final String BASEURL = "http://pin.taozhuma.com/v3.5/";//测试地址
    //public static final String BASEURL = "http://app.pindegood.com/v3.5/";//1.2~3.5正式地址
    //public static final String BASEURL = "http://app.pindegood.com/v3.6/";//3.6正式地址
    public static final String BASEURL = "http://pin.taozhuma.com/v3.6/";//3.6测试地址
    //public static final String BASEURL = "https://pin.taozhuma.com/v3.6/";//3.6测试地址 HTTPS


    public static final String CAPTCHA_URL = BASEURL + "captcha.do";//发送手机验证码
    public static final String USERLOGIN_URL = BASEURL + "userlogin.do";//登录
    public static final String DELFAVORITE_URL = BASEURL + "delFavorite.do";//取消收藏
    public static final String ADDFAVORITE_URL = BASEURL + "addFavorite.do";//添加收藏
    public static final String GETPRODUCTSKUS_URL = BASEURL + "getProductSkus.do";//商品SKU
    public static final String GUESSYOURLIKEAPI_URL = BASEURL + "guessYourLikeApi.do";//猜你喜欢
    public static final String SPECIALDETAIL_URL = BASEURL + "specialDetailApi.do";//专题详情
    public static final String SPECIALIMAGEAPI_URL = BASEURL + "specialImageApi.do";//专题图片
    public static final String NEWSPECIALIMAGEAPI_URL = BASEURL + "newSpecialImageApi.do";//新品专区顶部图片
    public static final String NEWSPECIALAPI_URL = BASEURL + "newSpecialApi.do";//新品专区
    public static final String ZONE_URL = BASEURL + "zoneApi.do";//专区信息
    public static final String ZONEPRODUCTS_URL = BASEURL + "zoneProductsApi.do";//专区商品列表
    public static final String QUERYPAYSTATUS_URL = BASEURL + "queryPayStatus.do";//订单付款同步处理
    public static final String GETPRODUCTINFOVIEW_URL = BASEURL + "getProductInfoView.do";//拼团/猜价-商品详情
    public static final String GETVALIDUSERCOUPON_URL = BASEURL + "getValidUserCoupon.do";//订单可用优惠券
    public static final String findGroupByTypeId = BASEURL + "findGroupByTypeId.do";//首页-根据分类查询拼团列表
    public static final String homeGroupProductApi = BASEURL + "homeGroupProductsApi.do";//首页-推荐拼团列表
    public static final String groupHomeApi = BASEURL + "groupHomeApi.do";//首页-平台广告轮播图
    public static final String productType = BASEURL + "productCategoryApi.do";//首页-二级分类
    public static final String groupByProductApi = BASEURL + "groupByProductApi.do";//首页-一个商品多个拼团列表
    public static final String orderDetailInfo = BASEURL + "orderDetailInfo.do";//订单单个产品详情
    public static final String payOrder = BASEURL + "payOrder.do";//订单付款
    public static final String editOrderStatus = BASEURL + "editOrderStatus.do";//确认订单
    public static final String addPurchase = BASEURL + "addPurchase.do";//直接购买
    public static final String addorder = BASEURL + "addorder.do";//提交订单
    public static final String myorder = BASEURL + "myorder.do";//我的订单
    public static final String cancelOrder = BASEURL + "cancelOrder.do";//取消订单
    public static final String orderDetailApi = BASEURL + "orderdetail.do";//订单详情
    public static final String guessBannerApi = BASEURL + "guessBannerApi.do";//猜价-顶部图片
    public static final String guessWinListApi = BASEURL + "guessWinListApi.do";//猜价-详情得奖人列表
    public static final String guessActivityApi = BASEURL + "guessActivityApi.do";//猜价-活动列表
    public static final String winListApi = BASEURL + "winListApi.do";//猜价-更多得奖人列表
    public static final String productFocusImagsApi = BASEURL + "productFocusImagsApi.do";//猜价-商品轮播图
    public static final String userJoinInfoApi = BASEURL + "userJoinInfoApi.do";//猜价-参与用户列表
    public static final String readyJoinApi = BASEURL + "readyJoinApi.do";//猜价-参与情况
    public static final String guessPriceApi = BASEURL + "guessPriceApi.do";//猜价-估价
    public static final String addFavorite = BASEURL + "addFavorite.do";//添加收藏
    public static final String isFavorite = BASEURL + "isFavorite.do";//收藏判断
    public static final String delSingleFavorite = BASEURL + "delSingleFavorite.do";//取消收藏（单个）
    public static final String delFavorite = BASEURL + "delFavorite.do";//取消收藏
    public static final String groupingListApi = BASEURL + "groupingListApi.do";//拼团-进行中的团
    public static final String openGroupActivityApi = BASEURL + "openGroupActivityApi.do";//拼团-开团页面
    public static final String GROUPDETAIL_URL = BASEURL + "groupDetailApi.do";//拼团-参团页面
    public static final String groupUserListApi = BASEURL + "groupUserListApi.do";//拼团-参团人列表
    public static final String selectAddress = BASEURL + "selectAddress.do";//设置默认地址(老接口)
    public static final String express = BASEURL + "express.do";//查看物流(老接口)
    public static final String defaultAddress = BASEURL + "defaultAddress.do";//我的-返回默认地址(老接口)
    public static final String myGuessListApi = BASEURL + "myGuessListApi.do";//我的-猜价列表
    public static final String myCollectListApi = BASEURL + "myCollectListApi.do";//我的-收藏列表
    public static final String myGroupListApi = BASEURL + "myGroupListApi.do";//我的-拼团列表
    public static final String myInfoApi = BASEURL + "myInfoApi.do";//我的-基本信息
    public static final String myaddress = BASEURL + "myaddress.do";//我的-地址列表(老接口)
    public static final String EditAddress = BASEURL + "eidtAddress.do";//我的-修改地址(老接口)
    public static final String getUserCouponList = BASEURL + "getUserCouponList.do";//我的-优惠卷列表(老接口)
    public static final String deleteAddress = BASEURL + "deleteAddress.do";//删除地址(老接口)
    public static final String addAddress = BASEURL + "addAddress.do";//我的-添加地址（老接口）
    public static final String addressDetailApi = BASEURL + "addressDetail.do";//我的地址详情
    public static final String groupFreeListApi = BASEURL + "groupFreeListApi.do";//团免列表
    public static final String checkGroupFreeApi = BASEURL + "checkGroupFreeApi.do";//团免-检查团免券
    public static final String searchAllProductApi = BASEURL + " searchAll.do";//搜索商品
    public static final String afterSaleListApi = BASEURL + "refundListApi.do";//售后列表
    public static final String applyRefundApi = BASEURL + "applyRefund.do";//申请退货/退款
    public static final String submitLogisticsApi = BASEURL + "submitLogistics.do";//填写物流信息
    public static final String addOrderByPurchaseApi = BASEURL + "addOrderByPurchase.do";//立即支付按钮
    public static final String refundDetailsApi = BASEURL + "refundDetails.do";//售后详情
    public static final String logisticsApi = BASEURL + "logistics.do";//快递公司
    public static final String getShareContentApi = BASEURL + "getShareContentApi.do";//获取分享内容
    public static final String refundExpressApi = BASEURL + "refundExpress.do";//退货物流接口
    public static final String specialTypeApi = BASEURL + "specialTypeApi.do";//专题分类
    public static final String specialListApi = BASEURL + "specialListApi.do";//专题列表
    public static final String sellOutListApi = BASEURL + "sellOutListApi.do";//今日售罄商品
    public static final String prizeBannerApi = BASEURL + "prizeBannerApi.do";//抽奖-顶部图片
    public static final String lotteryListApi = BASEURL + "getDrawListApi.do";//0.1抽奖列表
    public static final String getDrawApi = BASEURL + "getDrawApi.do";//我的抽奖列表
    public static final String prizeDetailApi = BASEURL + "prizeDetail.do";//中奖信息详情
    public static final String secKillListApi = BASEURL + "secKillListApi.do";//秒杀
    public static final String getDrawCommentDetailsApi = BASEURL + "getDrawCommentDetailsApi.do";//0.1抽奖评论详情
    public static final String actProductComment = BASEURL + "actProductComment.do";//我要晒图提交
    public static final String guessBeforeActivityApi = BASEURL + "guessBeforeActivityApi.do";//我要晒图提交
    public static final String callGuessCouponAlertApi = BASEURL + "callGuessCouponAlertApi.do";//修改优惠券弹窗未已弹窗
    public static final String freeDrawListApi = BASEURL + "freeDrawListApi.do";//免费抽奖列表
    public static final String activityBannerApi = BASEURL + "activityBannerApi.do";//活动图片
    public static final String findProductListApi = BASEURL + "findProductListApi.do";//根据分类查询商品列表
    public static final String homeSecKillListApi = BASEURL + "homeSecKillListApi.do";//首页秒杀商品
    public static final String myNoticeApi = BASEURL + "myNoticeApi.do";
    public static final String GAINCOUPON_URL = BASEURL + "gainCouponApi.do";//领取优惠券
    public static final String userOrderNoticeApi = BASEURL + "userOrderNoticeApi.do";//订单消息
    public static final String editUserInfoApi = BASEURL + " editUserInfo.do";//编辑用户信息
    public static final String geekValid = BASEURL + "geekValid.do";//极验开关
    public static final String ADDUSERCOUPON_URL = BASEURL + "addUserCoupon.do";//优惠券兑换
}
